jobs:
  - job: tests
    pool:
      vmImage: ubuntu-18.04
    strategy:
      matrix:
        Python36:
          python.version: 3.6
        Python37:
          python.version: 3.7
        Python38:
          python.version: 3.8
        PyPy3:
          python.version: pypy3
    steps:
      - task: UsePythonVersion@0
        inputs:
          versionSpec: $(python.version)
        displayName: Use Python $(python.version)
      - script: python -m pip install --upgrade pip setuptools tox virtualenv
        displayName: Install tox
      - script: tox -e py
        displayName: Run tests
      - script: .tox/py/bin/coverage xml
        displayName: generate coverage xml
      - task: PublishCodeCoverageResults@1
        inputs:
          codeCoverageTool: Cobertura
          summaryFileLocation: coverage.xml
        displayName: Publish coverage artifact

  - job: precommit
    pool:
      vmImage: ubuntu-18.04
    variables:
      PRE_COMMIT_HOME: $(Pipeline.Workspace)/pre-commit-cache
    steps:
      - task: UsePythonVersion@0
        inputs:
          versionSpec: 3.8
      - script: |
          echo "##vso[task.setvariable variable=PY]$(python -VV)"
        displayName: set version variables
      - task: Cache@2
        inputs:
          key: pre-commit | .pre-commit-config.yaml | "$(PY)"
          path: $(PRE_COMMIT_HOME)

  - job: docs
    pool:
      vmImage: ubuntu-18.04
    steps:
      - task: UsePythonVersion@0
        inputs:
          versionSpec: 3.8
      - script: python -m pip install --upgrade pip tox virtualenv
        displayName: Install dependencies
      - script: tox -e docs
        displayName: Build documentation
