jobs:
  - job: tests
    pool:
      vmImage: ubuntu-latest
    strategy:
      matrix:
        Python36:
          python.version: 3.6
        Python37:
          python.version: 3.7
        Python38:
          python.version: 3.8
        PyPy3:
          python.version: pypy3
    steps:
      - task: UsePythonVersion@0
        inputs:
          versionSpec: $(python.version)
        displayName: Use Python $(python.version)
      - script: python -m pip install --upgrade pip tox
        displayName: Install tox
      - script: tox -e py
        displayName: Run tests
      - script: .tox/py/bin/coverage xml
        displayName: generate coverage xml
      - task: PublishCodeCoverageResults@1
        inputs:
          codeCoverageTool: Cobertura
          summaryFileLocation: coverage.xml
        displayName: Publish coverage artifact

  - job: pre_commit
    pool:
      vmImage: ubuntu-latest
    steps:
      - task: UsePythonVersion@0
        inputs:
          versionSpec: 3.8
      - script: python -m pip install --upgrade pip tox
        displayName: Install tox
      - script: tox -e pre-commit
        displayName: Run pre-commit
