trigger:
  branches:
    include: [master, test-*]
  tags:
    include: ['*']

resources:
  repositories:
    - repository: aleksac
      type: github
      endpoint: AleksaC
      name: AleksaC/azure-pipelines-templates
      ref: refs/heads/master

jobs:
  - template: jobs/python-tests.yml@aleksac
    parameters:
      toxenvs: [ py36, py37, py38, py39, pypy3 ]

  - template: jobs/python-tests.yml@aleksac
    parameters:
      os: windows
      toxenvs: [ py38 ]

  - template: jobs/pre-commit.yml@aleksac

  - template: jobs/sphinx-docs.yml@aleksac
